# Generated by Django 5.1.5 on 2026-06-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='category_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='organisation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='availability_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='interests',
            field=models.TextField(blank=True),
        ),
    ]
