# Generated by Django 5.1.5 on 2026-06-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_organisation_verification_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('confirmee', 'Confirmee'), ('presente', 'Presente'), ('absente', 'Absente'), ('terminee', 'Terminee')], default='confirmee', max_length=20),
        ),
    ]
